name: Generate

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Download txts
        run: |
          export BASE_URL="https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash"
          wget -O blizzard.txt "$BASE_URL/Blizzard/Blizzard.yaml"
          wget -O disney.txt "$BASE_URL/Disney/Disney.yaml"
          wget -O github.txt "$BASE_URL/GitHub/GitHub.yaml"
          wget -O netflix.txt "$BASE_URL/Netflix/Netflix_Classical.yaml"
          wget -O spotify.txt "$BASE_URL/Spotify/Spotify.yaml"
          wget -O telegram.txt "$BASE_URL/Telegram/Telegram.list"

      - name: Generate yamls
        run: |
          function generate () {
            echo 'payload:' >"./yamls/$1-domain.yaml"
            grep '^DOMAIN-' "$1.txt" | awk -F ',' '{ print "  - " $2 }' >>"./yamls/$1-domain.yaml"
            echo 'payload:' >"./yamls/$1-ip-cidr.yaml"
            grep '^IP-CIDR' "$1.txt" | awk -F ',' '{ print "  - " $2 }' >>"./yamls/$1-ip-cidr.yaml"
          }

          mkdir ./yamls

          generate blizzard
          generate disney
          generate github
          generate netflix
          generate spotify
          generate telegram

      - name: Set release tag
        run: |
          TZ="Asia/Shanghai" echo "RELEASE_TAG=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
  
      - name: Release and upload yamls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          files: '*.yaml'

      - name: Git push yamls to release branch
        run: |
          cd yamls || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_TAG }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release

permissions:
  contents: write
