name: Generate

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Download txts
        run: |
          wget -O telegram.txt https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list

      - name: Generate yamls
        run: |
          mkdir ./yamls
          echo 'payload:' >telegram-domain.yaml
          grep '^DOMAIN-' telegram.txt | awk -F ',' '{ print "  - " $2 }' >>./yamls/telegram-domain.yaml

      - name: Set release tag
        run: |
          TZ="Asia/Shanghai" echo "RELEASE_TAG=$(date +%Y%m%d%H%M)" >>"$GITHUB_ENV"
  
      - name: Release and upload yamls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          files: '*.yaml'

      - name: Git push yamls to release branch
        run: |
          cd yamls || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_TAG }}"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f origin release

permissions:
  contents: write
